version: '2'
services:
  db:
    container_name: tpiaew-db
    entrypoint: /usr/db-entrypoint.sh
    image: mongo
    volumes:
      - ./db:/data/db
      - ./db-backup:/data/backup
      - ./db-backup/db-entrypoint.sh:/usr/db-entrypoint.sh

  backend:
    build: .
    container_name: tpiaew-backend
    image: tpiaew/backend
    environment:
      - DB=tpiaew-db
      - DEBUG=true
    volumes:
      - ./backend:/backend/
    depends_on:
      - db
    ports:
      - 3000:3000